# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/IP_Test/IP_Test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_Test || ORIG_REF_NAME==IP_Test} -quiet] -quiet

# IP: bd/IP_Test/ip/IP_Test_zynq_ultra_ps_e_0_0/IP_Test_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_Test_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==IP_Test_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/IP_Test/ip/IP_Test_rst_ps8_0_99M_0/IP_Test_rst_ps8_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_Test_rst_ps8_0_99M_0 || ORIG_REF_NAME==IP_Test_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/IP_Test/ip/IP_Test_ps8_0_axi_periph_0/IP_Test_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_Test_ps8_0_axi_periph_0 || ORIG_REF_NAME==IP_Test_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/IP_Test/ip/IP_Test_xbar_0/IP_Test_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_Test_xbar_0 || ORIG_REF_NAME==IP_Test_xbar_0} -quiet] -quiet

# IP: bd/IP_Test/ip/IP_Test_MemoryTestBlock_0_1/IP_Test_MemoryTestBlock_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_Test_MemoryTestBlock_0_1 || ORIG_REF_NAME==IP_Test_MemoryTestBlock_0_1} -quiet] -quiet

# IP: bd/IP_Test/ip/IP_Test_MemoryTestBlock_1_1/IP_Test_MemoryTestBlock_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_Test_MemoryTestBlock_1_1 || ORIG_REF_NAME==IP_Test_MemoryTestBlock_1_1} -quiet] -quiet

# IP: bd/IP_Test/ip/IP_Test_MemoryTestBlock_2_1/IP_Test_MemoryTestBlock_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_Test_MemoryTestBlock_2_1 || ORIG_REF_NAME==IP_Test_MemoryTestBlock_2_1} -quiet] -quiet

# IP: bd/IP_Test/ip/IP_Test_MemoryTestBlock_3_1/IP_Test_MemoryTestBlock_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_Test_MemoryTestBlock_3_1 || ORIG_REF_NAME==IP_Test_MemoryTestBlock_3_1} -quiet] -quiet

# IP: bd/IP_Test/ip/IP_Test_auto_ds_0/IP_Test_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_Test_auto_ds_0 || ORIG_REF_NAME==IP_Test_auto_ds_0} -quiet] -quiet

# IP: bd/IP_Test/ip/IP_Test_auto_pc_0/IP_Test_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_Test_auto_pc_0 || ORIG_REF_NAME==IP_Test_auto_pc_0} -quiet] -quiet

# XDC: bd/IP_Test/ip/IP_Test_zynq_ultra_ps_e_0_0/IP_Test_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: bd/IP_Test/ip/IP_Test_zynq_ultra_ps_e_0_0/IP_Test_zynq_ultra_ps_e_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==IP_Test_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==IP_Test_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/IP_Test/ip/IP_Test_rst_ps8_0_99M_0/IP_Test_rst_ps8_0_99M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==IP_Test_rst_ps8_0_99M_0 || ORIG_REF_NAME==IP_Test_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/IP_Test/ip/IP_Test_rst_ps8_0_99M_0/IP_Test_rst_ps8_0_99M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==IP_Test_rst_ps8_0_99M_0 || ORIG_REF_NAME==IP_Test_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/IP_Test/ip/IP_Test_auto_ds_0/IP_Test_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==IP_Test_auto_ds_0 || ORIG_REF_NAME==IP_Test_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/IP_Test/ip/IP_Test_auto_ds_0/IP_Test_auto_ds_0_ooc.xdc

# XDC: bd/IP_Test/ip/IP_Test_auto_pc_0/IP_Test_auto_pc_0_ooc.xdc

# XDC: bd/IP_Test/IP_Test_ooc.xdc
